export type WebRouterPaths = "/" | "/article/:slug" | "/blog" | "/blog/rss" | "/:slug" | "/admin/login" | "/admin/logout" | "/admin/forgot-password" | "/admin/reset-password" | "/admin" | "/admin/pages" | "/admin/pages/create" | "/admin/pages/edit/:id" | "/admin/pages/duplicate/:id" | "/admin/pages/delete/:id" | "/admin/users" | "/admin/users/create" | "/admin/users/edit/:id" | "/admin/users/block/:id" | "/admin/users/reset-password/:id" | "/admin/users/delete/:id" | "/admin/media" | "/admin/media/upload" | "/admin/media/delete/:id" | "/admin/blog" | "/admin/blog/create" | "/admin/blog/edit/:id" | "/admin/blog/duplicate/:id" | "/admin/blog/delete/:id" | "/admin/blog/settings" | "/admin/menu" | "/admin/settings" | "/admin/redirects" | "/admin/redirects/create" | "/admin/redirects/edit/:id" | "/admin/redirects/delete/:id" | "/admin/redirects/toggle/:id" | "/admin/profile";
export type ApiRouterPaths =
    | "/bootstrap"
    | "/auth/login"
    | "/dashboard"
    | "/pages"
    | "/pages/:id"
    | "/articles"
    | "/articles/:id"
    | "/blog-categories"
    | "/blog-categories/:id"
    | "/users"
    | "/users/:id"
    | "/media"
    | "/media/:id"
    | "/menu"
    | "/settings"
    | "/settings/:key"
    | "/redirects"
    | "/redirects/:id"
    | "/redirects/toggle/:id";
