export {
    ProductStatus, PRODUCT_STATUS_LABELS, PRODUCT_STATUS_VARIANTS,
    OrderStatus, ORDER_STATUS_LABELS, ORDER_STATUS_VARIANTS,
    CZECH_DIACRITICS_REPLACEMENTS,
} from "../../shared-keys";
